// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package simpleredisconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;
import redis.clients.jedis.Protocol;

public class Destroy extends CustomJavaAction<java.lang.Boolean>
{
	public Destroy(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			JedisPool pool = new JedisPool(new JedisPoolConfig(), simpleredisconnector.proxies.constants.Constants.getRedisURL(),
					Integer.valueOf(String.valueOf(simpleredisconnector.proxies.constants.Constants.getRedisPort())),
					Protocol.DEFAULT_TIMEOUT);
			pool.destroy();
		} catch (Exception e) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Error on Destroy action: " + e.getStackTrace());
		}
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Destroy";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
